### ISSUE TITLE
Backups are not always restorable

### ISSUE THREAD

**Issue by mrrogers75** [TapeWerm/MCscripts#18]
I had a bedrock server world that got corrupted, but when I went to load the backups they did not have everything. There were missing chunks and chunks that had been recreated to original. The server had been rebooted recently so I know the world wasn't corrupt before (at least not visibly). I think this might be similar to Issue #12, and that bedrock server is not creating live backup files correctly in the current release.

**Comment by TapeWerm** [comment]
Interesting, I know old versions of [MCBEbackup.sh](https://github.com/TapeWerm/MCscripts/blob/master/MCBEbackup.sh) had bugs where it would eat spaces or lose files due to tmux line wrapping but I fixed those in April 2019. In March 2020 I replaced tmux with journalctl and systemd pipes. It could also be the server executable. When did you last update MCBEbackup.sh? Sorry for past bugs if they caused any data loss.
Edit: [This commit](https://github.com/TapeWerm/MCscripts/commit/0af22e45301a4ffc4b11902f7f3d79f9da0e5de3) fixed the line wrap bug that ate spaces and lost files split by new lines. I searched `git log` for the word Fix/fix and could not find any other bugs that caused data corruption, nor do I remember any others. So if your MCBEbackup.sh is newer than that you shouldn't be missing files in your backup.

**Comment by TapeWerm** [comment]
From `bedrock_server_how_to.html`:

> After calling save hold you should call this command repeatedly to see if the preparation has finished. When it returns a success it will return a file list (with lengths for each file) of the files you need to copy. The server will not pause while this is happening, so some files can be modified while the backup is taking place. As long as you only copy the files in the given file list and truncate the copied files to the specified lengths, then the backup should be valid.

I wonder if `save query` forgets to list every file that needs to be copied. I could change MCBEbackup's behavior to copy all files, and then truncate only the ones listed. I don't know any world corruption that could result from having too many files. Could also be a bug in my script, either from the past (last fixed April 2019), or one that exists today that I don't know about.

**Comment by mrrogers75** [comment]
My MCBEbackup.sh script was last updated in April 2020. I think this is something in the server and not your script.

**Comment by TapeWerm** [comment]
Thanks for the info. I could make a branch that copies all files, not just the ones `save query` lists, if you want to test such. I have not seen the issue, though I rarely play much these days so I probably would not notice if a chunk that didn't occupy my home reverted.
Edit: Another theory is maybe the line listing the files from `save query` exceeds some max length and files get cut off.
Edit 2: If that's the case backups from when tmux was used (March 2020) might be intact. Or maybe tmux has a max line length too. If line length is an issue I feel like that would be an issue with the server in itself anyways.

**Comment by TapeWerm** [comment]
Line truncation theory seems broken. levelname.txt is always the last file listed, if the line truncated that file would be gone. I'm inclined to blame it on the server then. I might change my script to copy all files, not just the ones the server tells me to.
Edit:
```
May 22 21:47:42 glados MCBEbackup.sh[24960]:   adding: tA-TC_PE/db/102284.ldb (deflated 0%)
May 22 21:47:42 glados MCBEbackup.sh[24960]:   adding: tA-TC_PE/db/102273.ldb (stored 0%)
May 22 21:47:42 glados MCBEbackup.sh[24960]:   adding: tA-TC_PE/level.dat_old (deflated 43%)
May 22 21:47:42 glados MCBEbackup.sh[24960]:   adding: tA-TC_PE/levelname.txt (stored 0%)
May 22 21:47:42 glados MCBEbackup.sh[24960]:   adding: tA-TC_PE/level.dat (deflated 43%)
May 22 21:47:42 glados MCBEbackup.sh[24960]: Backup is /media/sdcard/MCBE_Backups/tA-TC_PE_Backups/2020/May/22_21-47.zip
May 22 21:47:42 glados systemd[1]: Started Back up Minecraft Bedrock Edition server world @ MCBE.
```

**Comment by TapeWerm** [comment]
https://github.com/TapeWerm/MCscripts/commit/03a97b3e07acf1680d82e011f19abfe2cb2114dc

This bug fix may or may not have been the culprit. This bug can only happen if you have more than 1 world in your server's `worlds` directory. I had a misleading variable name that was actually the parent dir of the world dir. Between Minecraft BDS 1.9 to 1.14, [BDS-1085](https://bugs.mojang.com/browse/BDS-1085) was a bug that did not give the correct path. It stripped the directories between the top dir and the file so only files directly under the top dir like `levelname.txt` had the right path. I used the `find` command to workaround this bug and complete the missing path, but the variable I used was actually 1 directory above what its name implied so there could be collision with a DB file from another world dir. Since Minecraft BDS 1.16 is out and that fixed BDS-1085, that buggy workaround won't even happen anymore, but I fixed it anyways in case BDS breaks `save query` again in a future update. I also fixed a couple other bugs in that commit as well. Sorry for not finding these earlier.

Edit: Such a bug would be obvious as your `levelname.txt` would be incorrect. So if it is this bug you should be able to check `levelname.txt`.

**Comment by zgibberish** [comment]
hey I have a bedrck server too, I tried copying all the files before like you said but that causes loss of in-game items. I changed the backup method to only copy files that the server lits but every time I load a saved backup the server tells me that there are missing ldb files.

**Comment by TapeWerm** [comment]
How did you change the backup method? What is the output of your server after save query? If you `echo "$files"` before the echo | read loop does it list them all?

**Comment by TapeWerm** [comment]
I should also note if you run a bedrock server backup in single-player you won't see your items because you will be the host player instead of your gamertag. Of course, missing ldb files sounds like a bigger issue.

**Comment by zgibberish** [comment]
no man, I meant that some random items in chests and sometimes even items im players's inventory or mobs disapper during backups. That happens quite a lot, like every day, sometimes a stack of gold ingots, one of my friend's horse disappeared while he was riding it.

**Comment by TapeWerm** [comment]
What is the list of files from save query? Example: `tA-TC_PE/db/272071.ldb:2147992, tA-TC_PE/db/272240.ldb:2130315, ...` When you stop the server does it say:
```
[INFO] Server stop requested.
[INFO] Stopping server...
Quit correctly
```
`journalctl -eu mcbe@MCBE` gives server output.

**Comment by zgibberish** [comment]
yea when I execute the save query command the server says that data is saved and a list of files like that. When I stop the server it also show those mesages, but if I run the server for a long period of time like over 3 hours, the server won't stop, it's stuck at ""Stopping server" so I had to implement a feature in my wrapper to kill the server process after 30 seconds if it does not stop by ítelf, I'm not sure if that's safe though.

**Comment by TapeWerm** [comment]
Killing the process may be unsafe. I've done it in the past without data loss but there is a possibility it could happen. Is CPU, RAM, or disk use high when you stop the server? If not it may be frozen so you'd have to kill the process. Even on an old system (Core i5 480M / 8GB 1066Mhz dual-channel RAM / 500GB 7200RPM hard drive / Ubuntu 20.04 Server / Minecraft bedrock server 1.17) with a 130MB world my old server stops in a few seconds.

Are you using [mcbe_backup.sh](https://github.com/TapeWerm/MCscripts/blob/master/mcbe_backup.sh) with a systemd service? Have you git pulled the latest version of MCscripts?

**Comment by zgibberish** [comment]
actually, I'n coding my own server wrapper in C# and I'm having the same backup issues as yours so I think we could discuss more about this. I'll try out your script and see if it helps.

**Comment by TapeWerm** [comment]
I fixed the issues I had with reading the list of LDB files long ago. It was a matter of getting the stdout from the server without line wrapping or truncation. Good luck with your code, but on that note I will close this issue as the issues you are having are not from my code.
