### ISSUE TITLE
Remove Java Support

### ISSUE THREAD

**Issue by jared-hess** [TapeWerm/MCscripts#24]
It was mentioned in some previous comments that nobody uses this for Java. That being the case, would it make sense to simply remove Java support? It might make maintenance and documentation a bit easier.

**Comment by TapeWerm** [comment]
I spoke figuratively about that. I personally have used it in the past, the Bedrock scripts were born from Java Edition. The lack of Bedrock backup scripts motivated me to open source this. That said I doubt many people use the Java services and scripts. It definitely would make maintenance easier, documentation doesn't really hurt much since I added that table of contents. I'll keep Java for now, it hasn't been much of a pain.
