### ISSUE TITLE
Multiple Bedrock Servers

### ISSUE THREAD

**Issue by mleo2003** [TapeWerm/MCscripts#49]
Am I right in thinking that, if I wanted to run a 2nd (or more) Bedrock server, that I should just follow the standard commands listed, changing "MCBE" to some other folder name in the setup directions, and update the server.properties file to point to a different UDP port for the clients to connect to?

My children started their own worlds on their devices, and I have saved a copy of their worlds so I can run it and not have them worried about who is online or not to run things, so I'd like to set up multiple running instances if I can easily, and your scripts have been a wonder in doing just that with 1 other world/server so far.

**Comment by TapeWerm** [comment]
Good thinking. Sometimes I try testing on a different instance than my personal server, and forget to change the port number. Hence the reminder on https://github.com/TapeWerm/MCscripts/blob/master/src/mcbe_setup.sh#L89 .

When I started writing MCscripts, I wasn't a good programmer and because I only ran 1 server, I didn't find bugs running multiple instances. I've considered writing some scripts to test MCscripts, but I haven't done so yet.

Another footgun might be firewalls. I use ufw, and I have wasted more than a few minutes before realizing I forgot to allow another port for a 2nd server.

**Comment by mleo2003** [comment]
Thanks, this worked great for me. Just for completeness, this is all what I ended up doing (to transfer worlds from an iOS device to here):

```
sudo /opt/MCscripts/mcbe_setup.sh TEST
mkdir /opt/MC/bedrock/TEST/worlds
cp -r /path/to/world-folder-here /opt/MC/bedrock/TEST/worlds/
chown -R mc:nogroup /opt/MC/bedrock/TEST/worlds/
vi /opt/MC/bedrock/TEST/server.properties
# edit level-name to match world folder name
# edit port to a new number that is unused
sudo systemctl enable mcbe@TEST.socket mcbe@TEST.service mcbe-backup@TEST.timer mcbe-autoupdate@TEST.service --now
```
