### ISSUE TITLE
Backup fails without helpful error message if server.properties contains CRLF line terminations

### ISSUE THREAD

**Issue by jared-hess** [TapeWerm/MCscripts#50]
Not sure if this is something you want to support or at least check for but might save someone else some time someday. Our server.properties file ended up with windows style (CRLF) line terminations, and while this doesn't cause an issue for the minecraft server, the backup script fails with the following:

```
Jun 13 23:45:30 rockbottom.bedrockorbust.com systemd[1]: Starting Back up Minecraft Bedrock Edition server world @ BedrockOrBust...
Jun 13 23:45:30 rockbottom.bedrockorbust.com mcbe_backup.sh[2671294]: [102B blob data]
Jun 13 23:45:30 rockbottom.bedrockorbust.com systemd[1]: mcbe-backup@BedrockOrBust.service: Main process exited, code=exited, status=1/FAILURE
Jun 13 23:45:30 rockbottom.bedrockorbust.com systemd[1]: mcbe-backup@BedrockOrBust.service: Failed with result 'exit-code'.
Jun 13 23:45:30 rockbottom.bedrockorbust.com systemd[1]: Failed to start Back up Minecraft Bedrock Edition server world @ BedrockOrBust.
```
It took some debugging to track down the cause. I resolved the issue by just using the dos2unix utility to convert the server.properties file. Basically the cut command grabs the CR character:
https://github.com/TapeWerm/MCscripts/blob/2fecdc79439d2c721eba4b4743d0cd6ae1187c44/src/mcbe_backup.sh#L79

You could instead use:
`world=$(basename -- "$(grep ^level-name= "$properties" | cut -d = -f 2- -s | tr -d '\r')")`
And just use that method any time you need to parse something from the settings file. Or maybe just check if the file contains CR characters and throw an error.

**Comment by TapeWerm** [comment]
Good find! I don't like to dismiss this as intended behavior, but I do like good error messages. I also don't like to blame others, but this seems to be default journalctl behavior.
```bash
# Convert UNIX line endings to DOS line endings
sudo sed -i 's/$/\r/' ~mc/bedrock/MCBE/server.properties
sudo systemctl start mcbe-backup@MCBE
journalctl -eu mcbe@MCBE -u mcbe-backup@MCBE -o cat
```
```
Starting Back up Minecraft Bedrock Edition server world @ MCBE...
No world Bedrock level^M in /opt/MC/bedrock/MCBE/worlds, check level-name in server.properties too
mcbe-backup@MCBE.service: Main process exited, code=exited, status=1/FAILURE
mcbe-backup@MCBE.service: Failed with result 'exit-code'.
Failed to start Back up Minecraft Bedrock Edition server world @ MCBE.
```
`man journalctl` and type `/^\ *-o` to regex search. I'll consider working around this. I'm not sure if I want to be nice programmer and just convert line endings like you suggest, or be mean programmer and escape the error message so journalctl doesn't try to hide it.

Related, I've been thinking about writing test scripts.  `man systemd.unit` and type `/override`. `z.conf` overrides `override.conf` and could configure test cases. I could make an instance named `mcbe@testme` with a high port number. Sometime this June I want to add tests, run them on Ubuntu 22.04 and 20.04, make Python 3 scripts default, and remove the Bash scripts later. [mcbe_backup.py](https://github.com/TapeWerm/MCscripts/blob/master/src/mcbe_backup.py) handles this case because of Python universal newlines. For now, I'll be maintaining both Bash and Python 3 scripts.

Edit:
I don't think this is relevant here, but in general, this is interesting behavior to break the `if [ ! -d "$worlds_dir/$world" ]` check. Might be good to review similar if statements with `git grep`.
```bash
vincent294@todd-howard:~/MCscripts/src$ if [ -d ~/"$yolo" ]; then echo 'Press [F]'; fi
Press [F]
vincent294@todd-howard:~/MCscripts/src$ yolo=respect
vincent294@todd-howard:~/MCscripts/src$ if [ -d ~/"$yolo" ]; then echo 'Press [F]'; fi
```
